name: cliving_front
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_provider: ^2.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  flutter_localization: ^0.2.0
  http: ^1.1.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  table_calendar: ^3.0.9
  curved_labeled_navigation_bar: ^2.0.2
  curved_nav_bar: ^0.0.2
  camera: ^0.10.5+9
  image_gallery_saver: ^2.0.3
  video_player: ^2.8.5
  flick_video_player: ^0.5.0
  wakelock: ^0.6.2
  cross_file_image: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.65.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:  
  #     - family: PretendardBold
  #       fonts:
  #       - asset: assets/font/Pretendard-Black.ttf


  #       - asset: assets/font/Pretendard-Bold.ttf
  #       - asset: assets/font/Pretendard-ExtraBold.ttf
  #       - asset: assets/font/Pretendard-ExtraLight.ttf
  #       - asset: assets/font/Pretendard-Light.ttf
  #       - asset: assets/font/Pretendard-Medium.ttf
  #       - asset: assets/font/Pretendard-Regular.ttf
  #       - asset: assets/font/Pretendard-SemiBold.ttf
  #       - asset: assets/font/Pretendard-Thin.ttf
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
